# ansible-playbook -i "150.95.132.109," ./script/create-user.yml -u root
- hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Add sudoers
      copy:
        content: "isucon  ALL=(ALL) NOPASSWD:ALL\n"
        dest: /etc/sudoers.d/90-isucon-user
        owner: root
        group: root
        mode: 0440
